### ISSUE TITLE
The struct attribute of rbatis2.5.30 cannot be converted and mapped to SQL

### ISSUE THREAD

**Issue by Tomao2014** [rbatis/rbatis#551]
您好，我尝试将 rbatis 从2.5.26 升级到更高的版本时，发现输出的SQL字段为空，入库失败。

环境：
```
Windows11
rust:  1.80.1
```

依赖：
```toml
rbs = { version = "4.5.18" }
rbatis = { version = "4.5.26" }
rbdc-mysql = { version = "4.5.8" }
```

`2.5.26`版本时，输出的SQL语句
```
`insert into x_table (id,name) VALUES (?,?),(?,?),(?,?)` [676345923466432515,"A",676345923466432521,"B",676345923466432522,"C"]
```

`2.5.28~2.5.30`时，输出的语句
```log
 `insert into x_table () VALUES (),()` []
```

请问是我哪里处理错误了吗

**Comment by zhuxiujia** [comment]
> 您好，我尝试将 rbatis 从2.5.26 升级到更高的版本时，发现输出的SQL字段为空，入库失败。
> 
> 环境：
> 
> ```
> Windows11
> rust:  1.80.1
> ```
> 
> 依赖：
> 
> ```toml
> rbs = { version = "4.5.18" }
> rbatis = { version = "4.5.26" }
> rbdc-mysql = { version = "4.5.8" }
> ```
> 
> `2.5.26`版本时，输出的SQL语句
> 
> ```
> `insert into x_table (id,name) VALUES (?,?),(?,?),(?,?)` [676345923466432515,"A",676345923466432521,"B",676345923466432522,"C"]
> ```
> 
> `2.5.28~2.5.30`时，输出的语句
> 
> ```
>  `insert into x_table () VALUES (),()` []
> ```
> 
> 请问是我哪里处理错误了吗

结构体是怎么写的？

**Comment by Tomao2014** [comment]
> > 您好，我尝试将 rbatis 从2.5.26 升级到更高的版本时，发现输出的SQL字段为空，入库失败。
> > 环境：
> > ```
> > Windows11
> > rust:  1.80.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 依赖：
> > ```toml
> > rbs = { version = "4.5.18" }
> > rbatis = { version = "4.5.26" }
> > rbdc-mysql = { version = "4.5.8" }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `2.5.26`版本时，输出的SQL语句
> > ```
> > `insert into x_table (id,name) VALUES (?,?),(?,?),(?,?)` [676345923466432515,"A",676345923466432521,"B",676345923466432522,"C"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `2.5.28~2.5.30`时，输出的语句
> > ```
> >  `insert into x_table () VALUES (),()` []
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问是我哪里处理错误了吗
> 
> 结构体是怎么写的？

你好，结构如下：
```
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Table {
    pub id: Option<i64>,  
    pub name: Option<String>,
}

impl Default for Table {
    fn default() -> Self {
        Self {
            id: Default::default(),
            name: Default::default(),
        }
    }
}

crud!(Table {}, "x_table");
```

**Comment by zhuxiujia** [comment]
最新版本没问题啊（你是不是用了国内的源了导致版本依赖有问题）
![1726154830277](https://github.com/user-attachments/assets/239baeb2-131b-4d77-ad9c-cc81522c3b98)

**Comment by Tomao2014** [comment]
> 最新版本没问题啊（你是不是用了国内的源了导致版本依赖有问题） ![1726154830277](https://private-user-images.githubusercontent.com/3481148/366948123-239baeb2-131b-4d77-ad9c-cc81522c3b98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTMyMjcsIm5iZiI6MTcyNjE5MjkyNywicGF0aCI6Ii8zNDgxMTQ4LzM2Njk0ODEyMy0yMzliYWViMi0xMzFiLTRkNzctYWQ5Yy1jYzgxNTIyYzNiOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDIwMjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzMxMTgxOGMzNDk1MGJjMDk2ZDRhNjJjMzMyZjM1NTQ0ZTI5NTg2YzY4OGNmMDVjZWI3NWU4N2M1NzBkNDllZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._ILxEwUGDfvImjp8eOeoG12A4NwmWprGCtnoxcbUhrE)

我一开始用的是字节的源，刚刚cargo clean，直接国外的源，发现问题还在存在。我暂时先用2.5.26吧。
而我下载项目源码，直接运行example中的crud_insert却是正常的，应该是我项目依赖冲突的问题，我后面再排查一下。以下是我项目的全部依赖：
```toml
[package]
name = "x-process"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["macros"] }        # 异步网络库
serde = { version = "1.0.210", features = ["derive"] }       # 一个超高性能的通用序列化/反序列化框架
serde_json = "1.0.128"                                       # JSON库
quick-xml = { version = "0.36.1", features = ["serialize"] } # 高性能XML库
anyhow = "1.0.87"                                            # 通用型错误处理库

# rbatis 数据库ORM
rbs = { version = "4.5.18" }
rbatis = { version = "4.5.30" }
rbdc-mysql = { version = "4.5.8" }

# 日志服务
log = "0.4.22"
fast_log = { version = "1.7.3", features = ["zip"] } # 日志库，可选压缩方式zip/lz4/gzip

json5 = "0.4.1" # json5格式文件解析
once_cell = "1.19.0" # 延迟加载全局变量的工具
flume = "0.11.0" # channel消息通道：mpmc(多发送者，多接收者)|更高的性能
futures = "0.3.30" # 管理和操作异步计算的核心库
dashmap = "6.1.0" # 并发安全的缓存库
sailfish = "0.9.0" # 模板引擎
uuid = "1.10.0"
regex = "1.10.6"
rocksdb = "0.22.0" # 嵌入式键值存储引擎
rmp-serde = "1.3.0" # MessagePack序列化与反序列化

[build-dependencies]
json5 = "0.4.1"
serde = { version = "1.0.210", features = ["derive"] } 
```
